[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/.netlify/functions/detect"
  status = 200

[[redirects]]
  from = "/index.html"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/data.json"
  to = "/data.json"
  status = 200